- id: pubmed:34861978

- id: pubmed:27725655

- id: pubmed:35702547

- id: pubmed:30038232

- id: pubmed:27090056

- id: pubmed:32371493

- id: pubmed:34396100

- id: pubmed:35276079

- id: doi:10.1038/s44220-023-00105-0

- id: doi:10.1038/s44220-023-00200-2
  image: "images/nmhasymmetry.png"

- id: pubmed:39144108
  title: N-acetylcysteine and a Specialized Preventive Intervention for Individuals at High Risk for Psychosis:\ a Randomized Double-Blind Multicenter Trial